// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: app/httpapi/config.proto

package httpapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Config is the settings for the optional REST/JSON HTTP API server.
type Config struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Listen   string                 `protobuf:"bytes,1,opt,name=listen,proto3" json:"listen,omitempty"`
	Username string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	// Default path for /api/config/import when "path" form field is empty.
	ConfigPath    string `protobuf:"bytes,4,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_app_httpapi_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_app_httpapi_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_app_httpapi_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetListen() string {
	if x != nil {
		return x.Listen
	}
	return ""
}

func (x *Config) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Config) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Config) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

var File_app_httpapi_config_proto protoreflect.FileDescriptor

const file_app_httpapi_config_proto_rawDesc = "" +
	"\n" +
	"\x18app/httpapi/config.proto\x12\x10xray.app.httpapi\"y\n" +
	"\x06Config\x12\x16\n" +
	"\x06listen\x18\x01 \x01(\tR\x06listen\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1f\n" +
	"\vconfig_path\x18\x04 \x01(\tR\n" +
	"configPathBR\n" +
	"\x14com.xray.app.httpapiP\x01Z%github.com/xtls/xray-core/app/httpapi\xaa\x02\x10Xray.App.Httpapib\x06proto3"

var (
	file_app_httpapi_config_proto_rawDescOnce sync.Once
	file_app_httpapi_config_proto_rawDescData []byte
)

func file_app_httpapi_config_proto_rawDescGZIP() []byte {
	file_app_httpapi_config_proto_rawDescOnce.Do(func() {
		file_app_httpapi_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_httpapi_config_proto_rawDesc), len(file_app_httpapi_config_proto_rawDesc)))
	})
	return file_app_httpapi_config_proto_rawDescData
}

var file_app_httpapi_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_app_httpapi_config_proto_goTypes = []any{
	(*Config)(nil), // 0: xray.app.httpapi.Config
}
var file_app_httpapi_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_httpapi_config_proto_init() }
func file_app_httpapi_config_proto_init() {
	if File_app_httpapi_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_httpapi_config_proto_rawDesc), len(file_app_httpapi_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_httpapi_config_proto_goTypes,
		DependencyIndexes: file_app_httpapi_config_proto_depIdxs,
		MessageInfos:      file_app_httpapi_config_proto_msgTypes,
	}.Build()
	File_app_httpapi_config_proto = out.File
	file_app_httpapi_config_proto_goTypes = nil
	file_app_httpapi_config_proto_depIdxs = nil
}
